### ISSUE TITLE
exit code not zero of command hibával elszáll a letöltés

### ISSUE THREAD

**Issue by xcom169** [wolandmaster/dijnet-dump#14]
"DFaktorhaz Zrt.", total: 7, current: 1ERROR: exit code not zero of command: INVOICE_COUNT=$(echo "${INVOICES}" | wc -w)

Terminated

**Comment by xcom169** [comment]
Újra előjött sajnos ez a hiba: 

ERROR: exit code not zero of command: INVOICE_COUNT=$(echo "${INVOICES}" | wc -w)                      ] 37% ETA 0:00:16
download "UPC", total: 32, current: 12,0  0:00:10 [==================>                                 ] 37%
Terminated

**Comment by wolandmaster** [comment]
Folyamatosan jon vagy csak alkalmankent?

**Comment by xcom169** [comment]
> 
> 
> Folyamatosan jon vagy csak alkalmankent?

Alkalmanként, néha teljesen végigmegy.

**Comment by xcom169** [comment]
Még mindig hibás sajnos:

download "NKM Foldgazszolgaltato", total: 37, current: 16ERROR: exit code not zero of command: INVOICE_COUNT=$(echo "${INVOICES}" | wc -w)

Terminated

**Comment by wolandmaster** [comment]
El tudnad kuldeni egy hibas futas kimenetet ugy, hogy a script elejere beirsz egy "set -x" -et.
A felhasznalonevet es jelszot csillagozd ki a kimenetben!

**Comment by xcom169** [comment]
[Szoveg.txt](https://github.com/wolandmaster/dijnet-dump/files/2984877/Szoveg.txt)

**Comment by xcom169** [comment]
> [Szoveg.txt](https://github.com/wolandmaster/dijnet-dump/files/2984877/Szoveg.txt)
Szia!
Csatoltam a fájlt.

**Comment by wolandmaster** [comment]
Jelentosen atirtam az egeszet, ki tudnad probalni, hogy meg mindig fennall-e a hiba.

**Comment by xcom169** [comment]
Szia!

Sajnos most meg ezt a hibát adja:

login... OK
query service providers... 9
hint: install "pv" package for a nice progress bar
download "Vodafone Cégcsoport", total: 23, current: 7ERROR: not able to select invoice

**Comment by wolandmaster** [comment]
Kerhetek ehhez is egy "set -x" -es futast amiben a felhasznalonevet es jelszot kitorlod?

**Comment by wolandmaster** [comment]
Ez valoszinuleg ugyanaz a hiba volt, mint a #29 -es, zarom az issue-t. Ha tovabbra is elojon a hiba kerlek nyiss egy ujat.
