### ISSUE TITLE
login... ERROR: login failed

### ISSUE THREAD

**Issue by NyariG** [wolandmaster/dijnet-dump#15]
login... ERROR: login failed
Befejeződött

Ezt kapom, gondolom azért mert megint variáltak rajta, valaki megtudná nézni mi baja?

**Comment by xcom169** [comment]
Nekem tegnap szépen lefutott.

**Comment by wolandmaster** [comment]
Nekem is mukodik, biztos jo felhasznalonev/jelszo parost hasznalsz?

**Comment by NyariG** [comment]
Igen, leelenőriztem, hogy tudnám debuggolni?

**Comment by wolandmaster** [comment]
Feltoltottem egy uj verziot a script-bol, ami kiirja, h mi volt a dijnet-tol visszakapott hibauzenet.

**Comment by NyariG** [comment]
Köszi de nálam még mindig ugyan azt szajkozza:

login... ERROR: login failed ()
Befejeződött


nyarig@Orig:~$ LOGIN=$(dijnet "login/login_check_password" "vfw_form=login_check_password&username=${USER}&password=${PASS}" | iconv -f iso8859-2 -t utf-8)
nyarig@Orig:~$ echo "${LOGIN}"

nyarig@Orig:~$ 

Gondolom ez a legnagyobb baj hogy én semmit nem kapok vissza. 



Sikerült debuggolni :) 
a wget hez hozzá kellett adni a „--no-check-certificate” kapcsolot máshogy nem akart kapcsolodni.
Viszont jött egy másik hiba.

**Comment by wolandmaster** [comment]
Jelentosen atirtam az egeszet, ki tudnad probalni, hogy meg mindig fennall-e a hiba.

**Comment by wolandmaster** [comment]
Ezt lezarom a #16 -os kapcsan megprobalom javitani a hibakat.
