### ISSUE TITLE
Nem tölti le a számlákat.

### ISSUE THREAD

**Issue by NyariG** [wolandmaster/dijnet-dump#16]
Most frissen lefutatva az eredmény az, hogy az upc nél talál 29 számlát ennek megcsinálja az UPC könyvtárat és létrehoz benne 29 üres könyvtárat szépen elnevezve. A telekom_mobilnál szintén. De csak üres könyvtárak vannak.

**Comment by hobpet** [comment]
Nekem letöltötte rendesen a UPC-ket is.

**Comment by attila-lendvai** [comment]
en is epp most clone-oztam/inditottam, es ugy tunik nekem is leszedett szepen mindent.

ezer koszi ezert a tool-ert!

**Comment by NyariG** [comment]
"szomorú" vagyok, hogy nektek müködik :) Ill annk örülök, csak azt nem tudom, hogy nálam mért nem szedi le a számlákat és mért csak üres könyvtárakat csinál...!?

**Comment by attila-lendvai** [comment]
@NyariG a .sh-ban a `wget --quiet`-bol szedd ki a `--quiet`-et, es nezd meg mit ir ki.

ha talalsz hibat, es nem tudod az alapjan megoldani, akkor rakd ide be comment-be a log-ot.

lehet pl valami https-es tema, nincs certificate-ed, vagy hasonlo.

**Comment by NyariG** [comment]
Igen, köszi a segítséget! a második `wget` be kimaradt a `--no-check-certificate` ezért nem töltötte le.

Most már jó!

Amúgy hogy hogy másnak megy e kapcsoló nélkül is?

**Comment by attila-lendvai** [comment]
@NyariG milyen oprendszeren vagy (verzio is)? az oprendreszben van egy lista a "megbizhato" certificate-ekrol, es az lehet, h nalad regi, vagy hibas/hianyos, es ezert a dijnet.hu SSL kulcsat nem fogadja el megbizhatonak...

**Comment by attila-lendvai** [comment]
ezt egyebkent nem szerencses fixen belerakni a dijnet script-be, mert ha valaki el akarja lopni a dijnet login-edet, es behazudja a sajat szerveret a dijnet.hu helyett a gepednek, akkor elkuldod neki a login-edet.

na persze ki akarja pont a dijnetet hack-elni...? meg az egesz SSL ellenorzes egy rossz vicc, amit a komolyabb szereplok (pl allamok) siman ki tudnak jatszani.

**Comment by NyariG** [comment]
DISTRIB_ID=neon
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="KDE neon User Edition 5.14"


A citrix cliens is hisztizik az ssl miatt. Hogy lehet ezt a listát frissiteni?

**Comment by wolandmaster** [comment]
Jelentosen atirtam az egeszet, ki tudnad probalni, hogy meg mindig fennall-e a hiba.

**Comment by NyariG** [comment]
Nekem már el sem indul:

```
NyariG@Origo2017:~$ dijnet6
bash: /home/NyariG/Bin/dijnet6: Engedély megtagadva
NyariG@Origo2017:~$ sudo dijnet6
[sudo] NyariG jelszava: 
sudo: dijnet6: parancs nem található
```

**Comment by wolandmaster** [comment]
Nem kell neki super user jog (sudo), van execute jog a script-en (chmod a+x dijnet-dump.sh)?
Mit ir ki ez a parancs?: /usr/bin/env bash

**Comment by NyariG** [comment]
Nem volt futtatható, most már jól lefut.

Egyedüli amit észrevettem, hogy korábban a Telekom mobil alatti mappaneveknél volt dátum most nincs csak a Vodafone Cégcsoporténál... érdekes, hogy egyiknél van a másiknál nincs.

**Comment by wolandmaster** [comment]
A legutobbi nagyobb update-nel atirtam, hogy a config file-ban legyen beallithato, hogy milyen mappaba mentse a szamlakat. Ezt a szamla letoltes ful alatti adatokbol veszi. Valoszinuleg a Telekom-nal valamit maskepp jelenit meg az oldal, de sajnos nekem nincs Telekom szamlam, igy nem tudom megnezni. Ha esetleg bongeszobol le tudnad mentni a Telekom szamla letoltes oldalat, akkor meg tudnam nezni, hogy mi a kulonbseg. Mielott elkuldod torold ki a szemelyes adatokat a html-bol.

**Comment by NyariG** [comment]
Itt van ha ez az amire gondoltál, Ha megnézted leszedted töröld légy szíves.
https://drive.google.com/drive/folders/15KZ2lzYmDIepUogRLn0IIfasYFeCzf10?usp=sharing

**Comment by wolandmaster** [comment]
Koszi, meglett a kulonbseg. A Telekomnal "Beerkezesi hatarido"-nek hivjak a "Fizetesi hatarido"-t.
Frissitettem a script-et, ki tudnad probalni? (Toroltem a minta file-okat)

**Comment by NyariG** [comment]
ez most nekem semmit nem tölt le, bejelentkezik kiirja hogy 2 a providers azt annyi...

```
nyarig@Origo201711:~/Letöltések$ dijnet7 ***** *****
login... OK
query service providers... 2
nyarig@Origo201711:~/Letöltések$ 
```

**Comment by wolandmaster** [comment]
Idokozben a dijnet megint valtoztatott az oldalon, nincs koze a Telekomos javitashoz a hibanak.
Most mar elvileg mennie kell.

**Comment by wolandmaster** [comment]
Lezarom a hibajegyet, abban bizva, hogy nalad is mukodik.

**Comment by NyariG** [comment]
Szia, bocsi, csak nem voltam eddig gépközelben. Müködik nálam is remekül! Köszi.
