### ISSUE TITLE
username folder

### ISSUE THREAD

**Issue by hobpet** [wolandmaster/dijnet-dump#17]
Lehet, hogy egyedi az eset, de én több fiókot kezelek, ezért jó lenne, ha username szinten is készülne egy folder.
Egy sor módosítás, meg is csináltam, ha esetleg másnak is hasznos lehet, mehet a pull request (https://github.com/hobpet/dijnet-dump/pull/new/master), ha csak nekem hasznos, zárjátok le az issue-t.

**Comment by BathoryPeter** [comment]
Nekem hasznos lenne, köszi a módosítást.

**Comment by wolandmaster** [comment]
Bekerult az en verziomba is (config file altal).
