### ISSUE TITLE
login... ERROR: login failed ()

### ISSUE THREAD

**Issue by zoltan-kiss-hungary** [wolandmaster/dijnet-dump#21]
Elhasal mar a belepesnel, a wget a nagy semmivel ter vissza. HAPROXY_SESSION es JSESSIONID cookie azert van. Mersekelten ertem csak, hogy hogy mukodnek az ilyen login formok, igy segitseget kernek a debugolashoz.

**Comment by wolandmaster** [comment]
Irj a script elejere egy "set -x" -et es akkor kiirja, hogy epp milyen parancsokat ad ki, igy egyszerubb lesz kezzel probalgatni.
(Nalam egyebkent mukodik a login es a letoltes)

Update: masoknak volt problemaja a https certificate-el, lasd itt: #15, #16. Lehet nalad is ez a baj.

**Comment by zoltan-kiss-hungary** [comment]
Néztem én is a cert-es issuekat, nálam nem oldotta meg a problémát. Beraktam a set -x-et, és kiszedtem a wget paraméterekból a quiet-et, lásd csatolt fájl. ([username] és [password]-re cseréltem az adataimat, amúgy többször kipróbáltam, azok jók).
Úgy néz ki hogy egy 0 hosszúságú választ kapok. Ha megnyitom a https://www.dijnet.hu/ekonto/login/login_check_password URL-t, akkor egyébként egy stylesheet nélküli oldalt hoz be először. Ide beírva a felhasználó nevemet és jelszavamat először azt mondja, hogy "Sikertelen bejelentkezés. Ellenőrizze adatait és próbálja újra!", a hibaüzenettel újratöltött oldal viszont már stylesheetel jelenik meg, és újra beírva az adataimat már bejelentkezik.
[login_empty_reply.txt](https://github.com/wolandmaster/dijnet-dump/files/3861115/login_empty_reply.txt)

**Comment by zoltan-kiss-hungary** [comment]
Egyébként 16.04 és 18.04-es Ubuntun is próbáltam, a wget verziók 1.17.1 és 1.19.4

**Comment by wolandmaster** [comment]
Bongeszobe beirva a login URL-t nekem is epp ugy viselkedik, mint ahogy te is irtad.
Kimasoltam a te logodbol a wget parancsot es az nalam szepen lefut. Egyebkent en is 18.04-en vagyok (wget: 1.19.4).

Kerlek probald ki a wget-et debug kapcsoloval, hatha okosabbak leszunk:
`wget --debug --output-document=- --save-cookies /tmp/cookies --keep-session-cookies --post-data 'vfw_form=login_check_password&username=[username]&password=[password]' https://www.dijnet.hu/ekonto/login/login_check_password`

**Comment by zoltan-kiss-hungary** [comment]
Kiprobaltam, lasd csatolt fajl. Ami viszont igazan erdekes, hogy csinaltam egy dummy usert, es azzal mukodik a login, ott persze nincsenek providerek igy elhasal annal a lepesnel. Aztan gondoltam egy meg mereszebbet, es kiprobaltam az "Ugyfelosszevonas" opciot: egy ujonnan letrehozott userrel vontam ossze a regi fiokot, igy atkerultek a regi szamlak es regisztraciok is. A poen, hogy osszevonas elott mukodott a login, utana meg megint ugyanerre a jelensegre futott. Lehet a useremmel van valami gond, netan az, hogy 2008 ota vagyok mar ott. A dummy userem tovabbra is mukodik.
[login_empty_reply_with_debug.txt](https://github.com/wolandmaster/dijnet-dump/files/3866473/login_empty_reply_with_debug.txt)

Illetve neha egy rovid relocate oldalt is dob a loginra, ha csak a wget parancsot futtatom kezzel, lasd masik csatolt fajl.

[relocate_page.txt](https://github.com/wolandmaster/dijnet-dump/files/3866475/relocate_page.txt)

**Comment by wolandmaster** [comment]
Jelentosen atirtam az egeszet, ki tudnad probalni, hogy meg mindig fennall-e a hiba.

**Comment by zoltan-kiss-hungary** [comment]
Szia!

Pont par hete neztem, akkor meg nem ment, most viszont mar elindult 
legalabb!
Eloszor nem ment vegig:

password:
login... OK
query service providers... 8
download "Fogyasztók", total: 1, current: 1.00  0:00:02 
[===========================================>] 100%
download "Kéményseprő", total: 1, current: 1.00  0:00:07 
[========================================>] 100%
download "Elmű", total: 37, current: 37.0  0:01:48 
[================================================>] 100%
ERROR: not able to select invoiceotal: 143, current:  129  0:07:27 
[=============================>    ] 90% ETA 0:00:48
download "Vodafone Cégcsoport", total: 143, current:  129  0:07:27 
[=============================>    ] 90%

De masodjara sikerult. Koszi!

Zoli

**Comment by wolandmaster** [comment]
Neha nekem is nagyon lassu vagy megall, de ez szerintem nem a script hibaja, hanem a dijnet.hu oldale.
