### ISSUE TITLE
dijnet-dump.sh: line 74: syntax error near unexpected token `<'

### ISSUE THREAD

**Issue by Merwenus** [wolandmaster/dijnet-dump#26]
1 év után Synology DSM 6.2.2-re telepítettem ezeket a szükséges libraryket:
`sudo ipkg install libxml2 libxslt`

Login működik, de rögtön erre a hibára fut:
```
login... OK
query service providers... dijnet-dump.sh: line 74: syntax error near unexpected token `<'
dijnet-dump.sh: line 74: `readarray -t PROVIDERS < <(dijnet "control/szamla_search" | perl -lne '/sopts.add\(.(.+?).\)/ and print $1')'
```

Hiányzik esetleg még valami az `libxml2 libxslt`-n kívül? Az 1 évvel ezelőtti fájlal ugyanez a hiba, de azt raspbianon futtattam, azóta az nyugdíjba vonult.

**Comment by wolandmaster** [comment]
Meg tavaly aprilisban be-merge-eltem egy [pull request](https://github.com/wolandmaster/dijnet-dump/commit/a306bebe65e6b0626b8202af5dfa08133184f66d)-et, ami behozott egy bash 4 -es dependenciat.
Meg tudnad nezni, hogy milyen bash-od van es, ha fent van a repo-ban, akkor ki kellene probalni bash 4-el.

**Comment by wolandmaster** [comment]
Oh, most latom, hogy perl is kerult bele. Nem voltam eleg alapos amikor megneztem a commit-ot.
A perl-t mindenkepp kiszedem, de, ha a bash4 nem problema, akkor megtartanam az associative array-t.

**Comment by Merwenus** [comment]
bash 4.3 van fent alapból, ha jól látom.

**Comment by wolandmaster** [comment]
Kivettem a perl-t es az associative array-t, illetve javitottam is a script-en, mert megint atirtak a dijnet-et.
Ki tudnad probalni?

**Comment by Merwenus** [comment]
Így lefut, de valamiért nem tölt le mindent.
FV Zrt. és FCSM lejön:
```
login... OK
query service providers... 2
hint: install "pv" package for a nice progress bar
download "FV Zrt.", total: 13, current: 12
download "FCSM Zrt.", total: 12, current: 11
```

De Főtáv, Díjbeszedő, Társ.díj_felosz, DFaktorház_Zrt, NKM nem, azokat fel se dobja mint találat.

**Comment by wolandmaster** [comment]
Kozben jelentosen atirtam az egeszet, ki tudnad probalni?

**Comment by Merwenus** [comment]
Aha, így láthatólag felismeri az összeset és tölti is őket. Annyi hátrányt veszek észre, hogy eddig ékezetes betűket használt (Díjbeszedő) most azok nincsenek (Dijbeszedo).
Így most duplikált minden mappát. Ha marad így, akkor régieket bemásolom az újba, ha módosítasz szólj, addig nem nyúlok hozzá. :)

**Comment by wolandmaster** [comment]
Igen, kiszedtem az ekezetes betuket a konyvtar nevekbol es igy is hagynam, szoval kerlek masold at a regieket.
Koszonom a tesztelest!
