### ISSUE TITLE
UTF-8 hibauzenet

### ISSUE THREAD

**Issue by pjuhasz** [wolandmaster/dijnet-dump#27]
Kiprobaltam az ujrairt kodot es ebben a pillanatban mukodik a letoltes, csak arra az aprosagra szeretnem felhivni a figyelmet, hogy idokozben a dijnet is megerkezett a 21. szazadba, es mar UTF-8 hibauzenetet kuld hibas bejelentkezeskor, es valoszinuleg maskor is. Igy az iconv kulon meghivasa mar nem szukseges, mert azzal egyutt ez lesz a hibauzenetbol:

ERROR: login failed (Sikertelen bejelentkezĂŠs. Ellenorizze adatait ĂŠs prĂłbĂĄlja Ăşjra!)

**Comment by wolandmaster** [comment]
Fura, mert ezt konkretan kiprobaltam es nekem kellett:
iconv nelkul:
  ERROR: login failed (Sikertelen bejelentkez�s. Ellenorizze adatait �s pr�b�lja �jra!)
iconv-al:
  ERROR: login failed (Sikertelen bejelentkezés. Ellenorizze adatait és próbálja újra!)

Lehet, hogy a LC/LANG beallitasok miatt maskepp viselkedik?...
Nalam ez van:
$ env | egrep "LC|LANG"
LC_MEASUREMENT=hu_HU.UTF-8
LC_PAPER=hu_HU.UTF-8
LC_MONETARY=hu_HU.UTF-8
LANG=en_US.UTF-8
LC_NAME=hu_HU.UTF-8
LC_ADDRESS=hu_HU.UTF-8
LC_NUMERIC=hu_HU.UTF-8
LC_TELEPHONE=hu_HU.UTF-8
LC_IDENTIFICATION=hu_HU.UTF-8
LC_TIME=hu_HU.UTF-8

Bar epp ezert raktam be a script futas elejere, hogy "export LANG=C". Hmm.
Neked mit ad a fenti parancs?

**Comment by wolandmaster** [comment]
Meg az a fura, hogy nekem meg a bongeszo is 8859-2 -t kap a login-ra:
![image](https://user-images.githubusercontent.com/4405909/84059576-213f5a80-a9bb-11ea-8b61-5374dfc10ae3.png)

**Comment by pjuhasz** [comment]
Valoban, a dijnet nekem is ISO-8859-2-ben valaszol. Az xpath a bunos: A $LOGIN valtozo tartalma meg ISO-8859-2, de amit az `xpath '//div[contains(@class, "alert")]/strong/text()' <<<"${LOGIN}"` csinal belole, az mar UTF-8 lesz.

A locale en-US.UTF-8.

Nalam az xpath a perl-XML-XPath-1.44-2.fc30 csomagbol jon.

A dolognak egyebkent nincs nagy jelentosege.

**Comment by wolandmaster** [comment]
Aham, szoval te az xmllint helyett perl scirpt-et hasznalsz az xpath-hoz.
Beleneztem a script-be es valoban bele van hardcode-olva az UTF-8 kimenet:
```
#!/usr/bin/perl

use strict;
use warnings;

$| = 1;

use utf8;
use XML::XPath;
use open ':std', ':encoding(UTF-8)';

...
```
