### ISSUE TITLE
konyvtar es file nevek, es azok sorbarendezese

### ISSUE THREAD

**Issue by attila-lendvai** [wolandmaster/dijnet-dump#28]
ha a file es konyvtar nevek elso resze a timestamp lenne valami fix es szabvanyos formatumban (pl 2020-06-08, iso-8601), akkor szepen sorban jonnenek a szamlak idorendben.

nem fontos, csak gondoltam bedobom az otletet.

**Comment by wolandmaster** [comment]
Ezt a meg tudod tenni, ha a config file-ban atirod a TARGET_FOLDER valtozot igy:
`TARGET_FOLDER="${INVOICE_PROVIDER}/${INVOICE_PAYMENT_DEADLINE}-${INVOICE_NUMBER}"`

vagy, ha nem a fizetesi hatarido datumat szeretned, hanem a szamla kiallitas datumat, akkor igy:
`TARGET_FOLDER="${INVOICE_PROVIDER}/${INVOICE_ISSUE_DATE}-${INVOICE_NUMBER}"`

**Comment by attila-lendvai** [comment]
koszi!

azt sejtettem, h at lehet irni valahol, de szerencsesebb lenne, ha ez lenne a default.

csak ugye a sok letoltott szamla, meg az inkrementalis letoltes... :/

**Comment by wolandmaster** [comment]
Gondolkoztam, hogy atirom, de nem akartam megvaltoztatni azt ahogyan evek ota mukodik. Valoszinuleg sokaknak az lenne furcsa, hogy eddig valamilyen formatumban mentette, de egy frissites utan meg egy masikban es vegyesen lennenek a regi es az uj konyvtarai.
Azert lett config file a script-hez, hogy mindenki ugy allithassa be maganak, ahogy szeretne (es esetleg kezzel atnevezhesse a regi menteseit).

**Comment by attila-lendvai** [comment]
erre egyebkent van egy megoldas:

1) uj app verzio, ami letrehozza a config file-t a regi default-al, ha az meg nincs ott

2) varakozas eleg sokaig, h minden regi user-nek legyen config file-ja

3) ujabb release, ami mar a "jo" default-al hozza letre a config file-t.


ha/amikor lehet detektalni, h ki az uj user (pl van valami installer hook), akkor konnyebb a helyzet, mert abbol letre lehet hozni a config file-t a jo default-al.

**Comment by attila-lendvai** [comment]
FTR, ezzel neveztem at a regi dir-eket (`-nono`=dry run):

```
rename -v -nono 's/(.*?)-(\d{4}).(\d{2}).(\d{2})$/$2.$3.$4-$1/' *
```
