### ISSUE TITLE
ERROR: not able to select invoice 

### ISSUE THREAD

**Issue by a5fuzet** [wolandmaster/dijnet-dump#29]
szia, evek ota boldog hasznaloja vagyok ennek a remek eszkoznek, halas koszonet erte:).

sajnos iden nem igazan boldogulok.

szamlak letoltese kozben, *NEM* mindig ugyanott, elszall a kovetkezo keppen:
@login03:~/dijnet_foutca/dijnet-dump$ ./dijnet-dump.sh
login... OK
query service providers... 6
hint: install "pv" package for a nice progress bar
download "Vodafone Cégcsoport", total: 11, current: 4ERROR: not able to select invoice

neha rogton az elso szamlanal, neha a 4-iknel, neha a masodik szolgaltatonal.

csak nalam van problema?

a kornyezet vmi egyetemi linux cluster node-ja, szoval lehet nem a leg up-to-date-ebb, de tavaly mukodott. 
dijnet dump a latest masterrol jon.

koszonom elore is ha megnezed!

**Comment by a5fuzet** [comment]
atneztem a tobbi hibajegynel, kertel egy "set -x"-es futast, bevallom, nem teljesen ertettem h mire gondoltal, en ezt probaltam ki:

XXXX@login03:~/dijnet_foutca/dijnet-dump$ set -x
+ set -x
++ pwd
++ kill -STOP 407

halaszi@login03:~/dijnet_foutca/dijnet-dump$ ./dijnet-dump.sh
+ ./dijnet-dump.sh
login... OK
query service providers... 6
hint: install "pv" package for a nice progress bar
download "Vodafone Cégcsoport", total: 11, current: 4ERROR: not able to select invoice

++ pwd
++ kill -STOP 407

**Comment by istvanrath** [comment]
Ugyanez nálam is (ugyanannál a szolgáltatónál: "Vodafone Cégcsoport")

**Comment by wolandmaster** [comment]
Sziasztok, 

En mult heten toltottem le a szamlakat es hiba nelkul lement, igaz nekem nincs Vodafone-os szamlam.

Nem a script elott kell "set -x", hanem benne.
Talan az a legegyszerubb, ha a conf file-ban kotoltod a usernevet es a jelszot es igy futtatod a script-et:

`bash -x dijnet-dump.sh 2> debug.log`

majd a keletkezett debug.log file-ban csereld le a felhasznaloneved es jelszavad (csillagokra) az osszes helyen.
Ha nem szeretned ide feltolteni, akkor kuldheted kozvetlen nekem is a debug.log-ot: sandor.balazsi@gmail.com

**Comment by istvanrath** [comment]
@wolandmaster  emailben elkuldtem.

**Comment by wolandmaster** [comment]
Koszi a logot! Sajnos nem volt eleg reszletes a loggolas, igy epp a lenyeg nem latszik belole. :-(
Annyit latok, hogy vmiert ket "Vodafone Cegcsoport" szolgaltato van benne, lehet ez kavar be valahol.

Keszitettem egy uj verziot a script-bol, ami elvileg mar hasznalhatobb debug logot fog generalni.
Bekerult egy uj kapcsolo is ("-d"), amit megadva debug log is generalodik es a lementett file-ban automatikusan kimaszkolodik a felhasznalonev es a jelszo.

Le tudnad futtatni ujra es el tudnad kuldeni a debug.log-ot?:

`./dijnet-dump.sh -d`

**Comment by istvanrath** [comment]
@wolandmaster küldtem újabb logot.

**Comment by wolandmaster** [comment]
Szerintem meglett a hiba oka, ki tudnad probalni? Koszi elore is.

**Comment by istvanrath** [comment]
Köszi! Most már rendesen végigfut, ugyanakkor azt nem teljesen értem, hogy mit csinál: nekem ugye 2 “Vodafone Cégcsoport”-os elődfizetésem is volt, így ezen kétszer megy végig, és mindkétszer 40 számlát tölt le, viszont a futás után 39db új alkönyvtárat látok. Én nézek be valamit?

**Comment by wolandmaster** [comment]
A script jelenleg a csak a "Vodafone Cégcsoport"-ra keres ra, igy nalad mind a ketszer kiadja a kulonbozo alias-u szamlakat. Osszesen 40 szamlad van, szoval elvileg 40 konyvtaradnak kellene lennie.
Ha neked csak 39 van, kerlek kuldd el a debug log-ot a teljes futasrol.

Szoval tudok olyat csinalni, hogy csak egyszer menjen vegig az azonos nevu szolgaltatokon, de akkor egy alkonyvtarban lesznek a kulonbozo alias-u szamlak, ugy mint most. Gondolom neked az lenne a jobb, ha kulon alkonyvtarakba kerulnenek. Megnezem, hogy ez megvalosithato-e.

**Comment by wolandmaster** [comment]
A legfrissebb verzio mar kezeli az azonos szolgaltatonal levo kulonbozo elofizeteseket.
Ha kulon alkonyvtarakba szeretned lementeni oket, megteheted, ha mondjuk ilyet adsz meg a config file-ban:

`TARGET_FOLDER="${INVOICE_PROVIDER}-${INVOICE_PROVIDER_ALIAS}/${INVOICE_NUMBER}-${INVOICE_PAYMENT_DEADLINE}"`

**Comment by wolandmaster** [comment]
@a5fuzet: meg tudnad nezni, hogy nalad is jol mukodik-e a legfrissebb verzio?

**Comment by wolandmaster** [comment]
Zarom a hibajegyet, @istvanrath megerositette, hogy mukodik es a javitott hiba illik az @a5fuzet altal vazolt viselkedesre.
