### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by sakos** [wolandmaster/dijnet-dump#3]
Több gépen is kipróbáltam és mindenütt Login failed hibaüzenetet kapok.
Természetesen ellenőriztem és jó usernév-jelszót adtam meg.

**Comment by bitvilag** [comment]
Még mindig aktuális a probléma?

**Comment by sakos** [comment]
A fene tudja. Azóta nem próbáltam. Találtam másik alkalmazást ami működött. 
Ha jól értem akkor be is fuccsolt a Díjnetnek ez a fizetős szolgáltatása.

**Comment by xcom169** [comment]
Tegnap nekem is rossz volt a login.
Ma megnézem majd újra.

**Comment by bitvilag** [comment]
Át kell írni 1 sort. Már pull requestet kértem, csak még nem fogadta el. Megváltozott a html tag

`-| grep -q "Bejelentkez&eacute;si n&eacute;v: </em>${USER}" || die "login failed"`
 `+| grep -q "Bejelentkez&eacute;si n&eacute;v: <strong>${USER}" || die "login failed"`

**Comment by xcom169** [comment]
Sajnos nekem így se megy.

**Comment by bitvilag** [comment]
Elsőre elírtam. Fontosak a html tag-ek. Mi a hiba? Esetleg kódrészletet, hátha tudok segíteni.

**Comment by xcom169** [comment]
Beírtam az új sort, de semmi változás sajnos.
| grep -q "Bejelentkezési név: ${USER}" || die "login failed"

login... ERROR: login failed
Terminated

Hol írjam még át a HTML tag-et?

**Comment by bitvilag** [comment]
mutass https://pastebin.com -on aktuálisan átírt változatot.
