### ISSUE TITLE
Vodafone cégcsoportot nem tölti

### ISSUE THREAD

**Issue by szogi** [wolandmaster/dijnet-dump#30]
> $ ./dijnet-dump.sh X
> password:
> login... OK
> query service providers... 1
> 

Log vége:

> + grep -c sopts.add
> + command -v pv
> + sed -n 's/.*var ropts\s*=\s*\[\(.*\)\];.*/\1/;s/},\s*{/}\n{/gp'
> + read -r PROVIDER_JSON
> + rm /tmp/tmp.71UZxKEgMZ

A 
sed -n 's/.*var ropts\s*=\s*\[\(.*\)\];.*/\1/;s/},\s*{/}\n{/gp'
nem stimmel rá, Ezek az értékek (az ügyfélszámokat kinulláztam):

    var sopts = new Set();
            sopts.add('\''Vodafone C.gcsoport'\'');

    ropts = [{"aliasnev":"UPC (0000000000)","szlaszolgnev":"Vodafone C.gcsoport","regszolgid":000000000,"ugyfelazon":"0000000000","statusgrp":40,"szolgid":210,"alias":"UPC"}];

**Comment by wolandmaster** [comment]
Javitva, koszonom. Ki tudnad probalni?

**Comment by szogi** [comment]
Köszi, jó lett! 👍 

> download "Vodafone Cegcsoport (UPC)", total: 30, current: 30.0  0:01:09 [==>] 100%
