### ISSUE TITLE
macOS: readlink parancs probléma

### ISSUE THREAD

**Issue by segabor** [wolandmaster/dijnet-dump#32]
Újabban a következő hibát produkálja a `dijnet-dump`:

```sh
Monarakh:dijnet-dump segabor$ ./dijnet-dump.sh ****
readlink: illegal option -- f
usage: readlink [-n] [file ...]
password: 
```

Úgy tűnik, a `readlink -f` macOS-en (talán más BSD variánsokon is) nem értelmezhető. Egy [másik projektnél nyitott hibajegyet](https://github.com/KittyKatt/screenFetch/issues/573) követve kiderült, hogy `stat -f`-fel működésre lehet bírni a szkriptet

**Comment by wolandmaster** [comment]
Felkerult a javitas, ki tudnad probalni?

**Comment by segabor** [comment]
Úgy tűnik, igen. A probléma elmúlt. Lezárom a hibajegyet ennek örömére. Köszönöm a javítást!
