### ISSUE TITLE
macOS: nem megy a bejelentkezés

### ISSUE THREAD

**Issue by segabor** [wolandmaster/dijnet-dump#33]
Nem működik macOS-en a bejelentkezés, hiába próbálok ki bármit:

```sh
Monarakh:dijnet-dump segabor$ ./dijnet-dump.sh -d ********
password: *******
login... 
ERROR: login failed ()
```

Ugyanez működik Linux alól. Erős a gyanúm, hogy esetünkben a `sed`-del lesz a gond, mivel ez sem ugyanaz (Linux vs BSD). Mindjárt feltelepítek egy GNU sed-et macOS-re és kipróbálom azzal.

**Comment by segabor** [comment]
Na igen, így már ment. Egy `brew install gnu-sed`, majd az összes `sed` kicserélése `gsed`-re megjavította a szkriptet.

**Comment by wolandmaster** [comment]
Beraktam, hogy ne kelljen kicserelgetni a `sed`-eket, ha telepitve van a `gsed`.

Esetleg ossze tudnad gyujteni, hogy mit kellett felrakni `brew`-val, hogy menjen a script? Beraknam az elejere, hogy irja ki.
Azt tudom, hogy `bash`-bol vmi osregi van alapbol, szoval azt biztos. Gondolom fel kellett rakni az `xxd`-t , ez melyik csomagbol jon? A `wget`-bol mukodik a macOS-es vagy abbol is GNU kell?

A `bash` beepitett fuggvenyein kivul a lenti parancsok vannak meg hasznalva a script-ben. Talan igy a legegyszerubb megkeresni, hogy melyik jon a `brew`-bol:

`type bash sed gsed grep tr dirname mktemp rm xxd wget`

**Comment by segabor** [comment]
Köszönöm a fixet @wolandmaster , működik!
A kért parancsok listája pedig:

```
bash is /usr/local/bin/bash
sed is /usr/bin/sed
gsed is /usr/local/bin/gsed
grep is /usr/bin/grep
tr is /usr/bin/tr
dirname is /usr/bin/dirname
mktemp is /usr/bin/mktemp
rm is /bin/rm
xxd is /usr/local/bin/xxd
wget is /usr/local/bin/wget
```

Ebből az `xxd` a vim csomagból(?) jön, azonban a macOS userlandje is tartalmazza, tehát szerintem abból nem kell csomagbeli verziót telepíteni. A wget-et telepítettem, viszont a macOS-nek van curl-je (ha számít).

**Comment by wolandmaster** [comment]
Szia, [osszeraktam](https://github.com/wolandmaster/dijnet-dump/commit/4944f865a79820a42986d78f599d60714a6ad83d) docker-ben egy [Darling](https://darlinghq.org/) alapu tesztkornyezetet `macOS`-hez. Ez alapjan [kiszedtem](https://github.com/wolandmaster/dijnet-dump/commit/835c9dc378c521e12f63acda478ea89de465930b) a gnu-sed dependenciat.
Ki tudnad probalni, hogy "valodi" `macOS`-en is jol mukodik-e a script?

**Comment by segabor** [comment]
Kipróbáltam pv-vel és anélkül. Működnek!
