### ISSUE TITLE
macOS: "fura" letöltés sorok

### ISSUE THREAD

**Issue by segabor** [wolandmaster/dijnet-dump#35]
A csatolt képen látszik, hogy a kiadott ESC szekvenciák nem értelmezettek, mert a  https://github.com/wolandmaster/dijnet-dump/blob/1a3cd5e4c090cd7d6b310e9032a746dbbde12bad/dijnet-dump.sh#L63 sorban az `xargs` után álló `echo` parancs nem a bash beépített függvénye, hanem helyette a macOS / BSD alapértelmezett `/bin/echo` parancsa hívódik meg, az pedig nem tud mit kezdeni a színekkel.

<img width="890" alt="dijnet-macos-download" src="https://user-images.githubusercontent.com/23614/105193666-05975780-5b39-11eb-84a1-71c4a65168bc.png">

**Comment by wolandmaster** [comment]
Nem szinek lennenek, hanem az aktualis sor torlese.

Atriom `printf`-re, ki tudnad probalni, hogy igy jol mukodik-e `macOS`-en?:

```
-    xargs -n 1 echo -ne "\033[2K\rdownload \"${PROVIDER_NAME}\", total: ${INVOICE_COUNT}, current:"; echo
+    xargs -n 1 printf "\033[2K\rdownload \"${PROVIDER_NAME}\", total: ${INVOICE_COUNT}, current: %d"; echo
```

**Comment by segabor** [comment]
Helyesbíteném magam, gondolom nem színeket jelentenek azok a szekvenciák, csak megoldják, hogy a kiírt sor frissül helyben. A `printf` úgy tűnik, megy. Mindig csak az a sor frissül, ami épp letöltődik.

**Comment by wolandmaster** [comment]
Koszonom, hogy jelezted a hibat, zarom a jegyet.
