### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by Celtic4785** [wolandmaster/dijnet-dump#39]
Hali!

Megint valami gondja van :(  (évekig működik, aztán behal)

login...   HTTP/1.1 406 Not Acceptable
  Date: Thu, 11 Aug 2022 08:51:28 GMT
  Content-Type: text/html
  Content-Length: 156
  Connection: close
  Server: HTTP-Server
  X-Frame-Options: SAMEORIGIN
  X-XSS-Protection: 1; mode=block
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin
  Strict-Transport-Security: max-age=31536000
  Front-End-Https: on
  Set-Cookie: HAPROXY_SESSION=as11|YvTDE; path=/; HttpOnly; Secure

ERROR: login failed ()

**Comment by artifexor** [comment]
Szerintem hasonló problémám volt nekem is és nekem az segített, hogy a user-agent-et beállítottam, szerintem szűrnek a wget request user agent-re. Miután a wget soroknál hozzáadtam a user agent-et, működött. (például wget --quiet  helyett wget --quiet --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0")

**Comment by halacs** [comment]
Miután ezt a patchet megcsináltam a fenti javaslat alapján nálam is újra működik. Lehet mindjárt csinálok egy pull requestet rá.

```
diff --git a/dijnet-dump.sh b/dijnet-dump.sh
index 81c4449..da2a94c 100755
--- a/dijnet-dump.sh
+++ b/dijnet-dump.sh
@@ -13,6 +13,8 @@ if ! type xmllint wget xxd &>/dev/null || [[ ${BASH_VERSINFO[0]} < 4 ]]; then
   exit 1
 fi
 
+USER_AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"
+
 die() {
   EXIT_CODE="$?" && printf "$*" >&2 && exit 1
 }
@@ -37,7 +39,7 @@ unaccent() {
 
 dijnet() {
   URL_POSTFIX="$1"; shift; local IFS=""; POST_DATA="$*"
-  wget --quiet --output-document=- --post-data "${POST_DATA}" --no-check-certificate \
+  wget --quiet --user-agent "${USER_AGENT}" --output-document=- --post-data "${POST_DATA}" --no-check-certificate \
        --load-cookies "${COOKIES}" --save-cookies "${COOKIES}" --keep-session-cookies \
        "${DIJNET_BASE_URL}/${URL_POSTFIX}"
 }
@@ -52,7 +54,7 @@ download_internal_links() {
   LINKS=$(tr -d '\n' <<<"${HREFS}" | sed -E $'s/[[:space:]]*href="//g;s/"[[:space:]]*/\\\n/g')
   for LINK in ${LINKS}; do
     grep -q "^http" <<<"${LINK}" && continue
-    wget --quiet --load-cookies "${COOKIES}" --content-disposition --no-clobber --no-check-certificate \
+    wget --quiet --user-agent "${USER_AGENT}" --load-cookies "${COOKIES}" --content-disposition --no-clobber --no-check-certificate \
          --directory-prefix "${FIXED_TARGET_FOLDER}" "${DIJNET_BASE_URL}/ekonto/control/${LINK}"
   done
 }

```

**Comment by halacs** [comment]
@wolandmaster Rá tudsz kérlek nyomni a pull requestemre? Köszi!

**Comment by Celtic4785** [comment]
> Szerintem hasonló problémám volt nekem is és nekem az segített, hogy a user-agent-et beállítottam, szerintem szűrnek a wget request user agent-re. Miután a wget soroknál hozzáadtam a user agent-et, működött. (például wget --quiet helyett wget --quiet --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0")

Köszi, tökéletes :) 
Újra boldog vagyok.

**Comment by wolandmaster** [comment]
Koszi a javitast!
