### ISSUE TITLE
ERROR: login failed ()

### ISSUE THREAD

**Issue by halacs** [wolandmaster/dijnet-dump#41]
Sziasztok!

Újabban ezt a hibát mondja amikor próbálom letölteni a számlákat.
Semmi nem változott a beállításokon, ugyanazzal a loginnal böngészőből működik.
UserAgent stringet próbáltam módosítani de nem segít.

```
login... 
ERROR: login failed ()
```

**Comment by wolandmaster** [comment]
Szia!

Adaptaltam a script-et a dijnet valtozasaihoz. Kerlek probald ki!

**Comment by halacs** [comment]
Király vagy! Működik! :) Köszönöm!

**Comment by Celtic4785** [comment]
Köszi, működik.
