### ISSUE TITLE
Nem találja a szolgáltatók listáját és kilép

### ISSUE THREAD

**Issue by artifexor** [wolandmaster/dijnet-dump#44]
Ma le akartam tölteni a számláim és kilép a program, 'ERROR: not able to detect service providers' szöveggel die-ol. Amire jutottam, hogy az ekonto/control/szamla_search oldalt ha böngészőben nyitom meg, akkor benne van a szolgáltatólista és a sopts.add sorok, viszont a script futtatásakor, a debug kimenetben semmi ilyen sincs benne, ezért a hiba. A böngésző agent-et megnézem és bemásoltam a konfigurációba, tehát azonos a böngésző és a script esetén. Esetleg dinamikusan tölthetik be a listát?

**Comment by halacs** [comment]
Nem biztos, hogy végig fogom tudni vinni a dolgot, de azt már látom, hogy nem javascript generálja bele azokat a bizonyos
```var sopts = new Set();```
kezdetű sorokat. Valami más ármányság lesz itt.

Megnéztem a böngészőben lejövő tartalmat. Abból a böngésző generált egy `curl` hívást amit bashben futtatva látszanak azok a bizonyos sorok.

**Comment by halacs** [comment]
Nem jutottam sajnos előbbre mi alapján dönti el a szerver vissza adja e azokat a sorokat.

**Comment by wolandmaster** [comment]
Holnap megnezem a dolgot!

**Comment by artifexor** [comment]
Én annyit látok, hogy FF alatt 'view page source' mutatja a sopts-ot, a dijnet script debug kimenet, ami elméletileg a wget kimenete, ott nincsen, ezért nem is találja. Név és társai ott vannak, a még nem befizetett számla benne van, tehát a login sikeres volt. Az agent-et is átírtam arra, amit az FF-em ad, abban se legyen különbség.

**Comment by wolandmaster** [comment]
Sziasztok! Javítottam a hibát, kérlek próbáljátok ki.

**Comment by halacs** [comment]
Működik! Király! 

Jól látom, hogy a `sopts` sorokat illetően a gond az volt, hogy POST kérés ment GET helyett? Cink hogy nem vettem észre :D Hiba volt abból kiindulni, hogy biztos a script ellehetetlenítése a cél :)

**Comment by wolandmaster** [comment]
Igen, úgy fest már eleve rosszul írtam meg, de eddig hajlandó volt válaszolni az oldal az empty body-s POST-okra is :-)
Emellett valamiért beraktak egy egyszer használható tokent is a számla kereséshez.
Szerintem nincs tudomásuk a script-ről, vagy nem érdekli őket. Ha nagyon akarnák be tudnának rakni olyat amit nem nagyon lehet lekezelni wget-el, de akkor meg atírnám [Puppeteer](https://pptr.dev/)-re és azt nem lehet ellehetetleníteni... ;-)
