### ISSUE TITLE
service providers not found

### ISSUE THREAD

**Issue by kbalint** [wolandmaster/dijnet-dump#5]
helló, nálam a kurrens verzió ezt mondja:

login... OK
query service providers... ERROR: not able to detect service providers
Terminated

- pedig van két aktív és két megszűnt providerem. mit tudok tenni?

**Comment by agostonl119** [comment]
Nálam is ugyanez van!

**Comment by gyuri-szing** [comment]
Nekem akkor irta ezt, ha nem volt fent xmllint. Debian alapu disztrokban: apt-get install libxml2-utils. Cygwin -ben a libxml2 csomag kell (setup-x86_64 -qP libxml2).

**Comment by kbalint** [comment]
wow és tényleg, működik, köszi! esetleg egy ellenőrzést az elejére, hogy megvan-e a csomag-dependencia? :)

**Comment by agostonl119** [comment]
Köszönöm, elindult. Jah dependencia check... Aztán akár lehetne .deb fájl is belőle. ;)
Még1x köszi!

**Comment by wolandmaster** [comment]
Automatikus ellenorzes valoban nincs, de a script elejere egyebkent odairtam... ;-)
