### ISSUE TITLE
macOS Sierra alatt nem enged be

### ISSUE THREAD

**Issue by ironiq** [wolandmaster/dijnet-dump#6]
Szia,

macOS 10.12 alatt a login nem működik, nem találja meg az adott stringet a wget-tel letöltött htmlben. Kicsit mókoltam vele és kisült, hogy a html latin2-ben jön le. On-the-fly konvertálva (iconv) utf8-ra simán működött.

IroNiQ

**Comment by wolandmaster** [comment]
Koszi, javitottam.
