### ISSUE TITLE
Pontra végződő szolgáltatónév

### ISSUE THREAD

**Issue by ZsKokos** [wolandmaster/dijnet-dump#7]
Cygwin mkdir nem tudja a mappát létrehozni, ha a szolgáltató neve pont (.) karakterre végződik.
Példa: FV Zrt.

Workaround: TARGET_FOLDERben a ${PROVIDER} végére odabiggyesztünk valamilyen karaktert.

**Comment by wolandmaster** [comment]
Javitva, koszi.
